version: "3.9"

services:
  db:
    image: postgres:15
    container_name: mobility-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: mobility-app
    depends_on:
      - db
    env_file:
      - .env.docker
    command: sh -c "sleep 5 && npx prisma migrate deploy && npx ts-node prisma/seed/seed.ts && npm run dev"
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app

volumes:
  postgres_data:
